export const db = [
  {
    id: 1,
    fullName: 'Niraj Mehta',
    company: 'Yotz PVT LTD',
    role: 'developer',
    username: 'gslixby0',
    country: 'El Salvador',
    contact: '(479) 232-9151',
    email: 'niraj@threatreaper.io',
    currentPlan: 'enterprise',
    status: 'active',
    avatar: '',
    avatarColor: 'primary'
  },
  {
    id: 2,
    fullName: 'Rahil Gandhi',
    company: 'Skinder PVT LTD',
    role: 'devops',
    username: 'hredmore1',
    country: 'Albania',
    contact: '(472) 607-9137',
    email: 'rahil@threatreaper.io',
    currentPlan: 'team',
    status: 'active',
    avatar: '/images/avatars/3.png'
  },
  {
    id: 3,
    fullName: 'Chandan Mishra',
    company: 'Oozz PVT LTD',
    role: 'Engineering Manager',
    username: 'msicely2',
    country: 'Russia',
    contact: '(321) 264-4599',
    email: 'chandan@threatreaper.io',
    currentPlan: 'enterprise',
    status: 'active',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 4,
    fullName: 'Keval Mehta',
    company: 'Oozz PVT LTD',
    role: 'devsecops',
    username: 'crisby3',
    country: 'China',
    contact: '(923) 690-6806',
    email: 'keval@threatreaper.io',
    currentPlan: 'team',
    status: 'active',
    avatar: '/images/avatars/3.png'
  },
  {
    id: 5,
    fullName: 'Maggy Hurran',
    company: 'Aimbo PVT LTD',
    role: 'Security Lead',
    username: 'mhurran4',
    country: 'Pakistan',
    contact: '(669) 914-1078',
    email: 'maggy@threatreaper.io',
    currentPlan: 'enterprise',
    status: 'pending',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 6,
    fullName: 'Silvain Halstead',
    company: 'Jaxbean PVT LTD',
    role: 'Security Engineer',
    username: 'shalstead5',
    country: 'China',
    contact: '(958) 973-3093',
    email: 'silvain@threatreaper.io',
    currentPlan: 'company',
    status: 'active',
    avatar: '',
    avatarColor: 'error'
  },
  {
    id: 7,
    fullName: 'Breena Gallemore',
    company: 'Jazzy PVT LTD',
    role: 'Full Admin',
    username: 'bgallemore6',
    country: 'Canada',
    contact: '(825) 977-8152',
    email: 'breena@threatreaper.io',
    currentPlan: 'company',
    status: 'pending',
    avatar: '',
    avatarColor: 'warning'
  },
  {
    id: 8,
    fullName: 'Kathryne Woods',
    company: 'Pixoboo PVT LTD',
    role: 'LimitedView',
    username: 'kliger7',
    country: 'France',
    contact: '(187) 440-0934',
    email: 'kathryne@threatreaper.io',
    currentPlan: 'enterprise',
    status: 'pending',
    avatar: '/images/avatars/4.png'
  },
  {
    id: 9,
    fullName: 'Abhishek Sharma',
    company: 'Tekfly PVT LTD',
    role: 'temporaryPlanAccess',
    username: 'fscotfurth8',
    country: 'China',
    contact: '(978) 146-5443',
    email: 'abhishek@threatreaper.io',
    currentPlan: 'team',
    status: 'pending',
    avatar: '/images/avatars/2.png'
  },
  {
    id: 10,
    fullName: 'RajShekar K',
    company: 'Gigashots PVT LTD',
    role: 'Monitoring Team',
    username: 'jbellany9',
    country: 'Jamaica',
    contact: '(589) 284-6732',
    email: 'rajshekar@threatreaper.io',
    currentPlan: 'company',
    status: 'inactive',
    avatar: '/images/avatars/5.png'
  }
]
